---
- name: Install required system packages
  yum:
    name:
      - docker
      - python3-pip
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-`uname -s`-`uname -m`"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create project directory
  file:
    path: /home/ec2-user/docker-wordpress-app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/ec2-user/docker-wordpress-app/docker-compose.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Launch Docker Compose
  shell: docker-compose up -d
  args:
    chdir: /home/ec2-user/docker-wordpress-app

